// UAE Emirates
export const emirates = [
    { code: 'AUH', name: 'Abu Dhabi' },
    { code: 'DXB', name: 'Dubai' },
    { code: 'SHJ', name: 'Sharjah' },
    { code: 'AJM', name: 'Ajman' },
    { code: 'UAQ', name: 'Umm Al Quwain' },
    { code: 'RAK', name: 'Ras Al Khaimah' },
    { code: 'FJR', name: 'Fujairah' }
  ];
  
  // Saudi Arabia Regions
  export const saudiRegions = [
    { code: 'RIY', name: 'Riyadh' },
    { code: 'MKK', name: 'Makkah' },
    { code: 'MED', name: 'Madinah' },
    { code: 'EPR', name: 'Eastern Province' },
    { code: 'QAS', name: 'Qassim' },
    { code: 'HAI', name: 'Hail' },
    { code: 'NOR', name: 'Northern Borders' },
    { code: 'JAZ', name: 'Jazan' },
    { code: 'NAJ', name: 'Najran' },
    { code: 'BAH', name: 'Al-Baha' },
    { code: 'ASI', name: 'Asir' },
    { code: 'TAB', name: 'Tabuk' },
    { code: 'JOU', name: 'Al-Jouf' }
  ];
  
  // US States
  export const usStates = [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" }
  ];
  
  // UK Subdivisions
  export const ukSubdivisions = [
    { code: 'ENG', name: 'England' },
    { code: 'EAW', name: 'England and Wales' },
    { code: 'LND', name: 'London' },
    { code: 'NW', name: 'North West England' },
    { code: 'NE', name: 'North East England' },
    { code: 'EM', name: 'East Midlands' },
    { code: 'WM', name: 'West Midlands' },
    { code: 'EE', name: 'East of England' },
    { code: 'SE', name: 'South East England' },
    { code: 'SW', name: 'South West England' },
    { code: 'YH', name: 'Yorkshire and the Humber' },
    { code: 'SCT', name: 'Scotland' },
    { code: 'WLS', name: 'Wales' },
    { code: 'NIR', name: 'Northern Ireland' }
  ];
  
  // France Regions
  export const franceRegions = [
    { code: 'FR-ARA', name: 'Auvergne-Rhône-Alpes' },
    { code: 'FR-BFC', name: 'Bourgogne-Franche-Comté' },
    { code: 'FR-BRE', name: 'Brittany (Bretagne)' },
    { code: 'FR-CVL', name: 'Centre-Val de Loire' },
    { code: 'FR-COR', name: 'Corsica (Corse)' },
    { code: 'FR-GES', name: 'Grand Est' },
    { code: 'FR-HDF', name: 'Hauts-de-France' },
    { code: 'FR-IDF', name: 'Île-de-France' },
    { code: 'FR-NOR', name: 'Normandy (Normandie)' },
    { code: 'FR-NAQ', name: 'Nouvelle-Aquitaine' },
    { code: 'FR-OCC', name: 'Occitanie' },
    { code: 'FR-PDL', name: 'Pays de la Loire' },
    { code: 'FR-PAC', name: 'Provence-Alpes-Côte d’Azur' },
    { code: 'FR-GUA', name: 'Guadeloupe' },
    { code: 'FR-GF', name: 'French Guiana (Guyane)' },
    { code: 'FR-MQ', name: 'Martinique' },
    { code: 'FR-RE', name: 'Réunion' },
    { code: 'FR-MAY', name: 'Mayotte' }
  ];
  
  // Germany States
  export const germanStates = [
    { code: 'BW', name: 'Baden-Württemberg' },
    { code: 'BY', name: 'Bavaria (Bayern)' },
    { code: 'BE', name: 'Berlin' },
    { code: 'BB', name: 'Brandenburg' },
    { code: 'HB', name: 'Bremen' },
    { code: 'HH', name: 'Hamburg' },
    { code: 'HE', name: 'Hesse (Hessen)' },
    { code: 'NI', name: 'Lower Saxony (Niedersachsen)' },
    { code: 'MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'NW', name: 'North Rhine-Westphalia (NRW)' },
    { code: 'RP', name: 'Rhineland-Palatinate (Rheinland-Pfalz)' },
    { code: 'SL', name: 'Saarland' },
    { code: 'SN', name: 'Saxony (Sachsen)' },
    { code: 'ST', name: 'Saxony-Anhalt (Sachsen-Anhalt)' },
    { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'TH', name: 'Thuringia (Thüringen)' }
  ];
  
  // India States and Union Territories
  export const indianSubdivisions = [
    { code: 'AN', name: 'Andaman and Nicobar Islands' },
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CH', name: 'Chandigarh' },
    { code: 'CT', name: 'Chhattisgarh' },
    { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
    { code: 'DL', name: 'Delhi (NCT)' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu and Kashmir' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'LA', name: 'Ladakh' },
    { code: 'LD', name: 'Lakshadweep' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OR', name: 'Odisha' },
    { code: 'PY', name: 'Puducherry' },
    { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TG', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UT', name: 'Uttarakhand' },
    { code: 'WB', name: 'West Bengal' }
  ];
  
  // China Subdivisions
  export const chinaSubdivisions = [
    { code: 'BJ', name: 'Beijing (Municipality)' },
    { code: 'SH', name: 'Shanghai (Municipality)' },
    { code: 'TJ', name: 'Tianjin (Municipality)' },
    { code: 'CQ', name: 'Chongqing (Municipality)' },
    { code: 'HE', name: 'Hebei' },
    { code: 'SX', name: 'Shanxi' },
    { code: 'NM', name: 'Inner Mongolia (Autonomous Region)' },
    { code: 'LN', name: 'Liaoning' },
    { code: 'JL', name: 'Jilin' },
    { code: 'HL', name: 'Heilongjiang' },
    { code: 'SHD', name: 'Shandong' },
    { code: 'JS', name: 'Jiangsu' },
    { code: 'ZJ', name: 'Zhejiang' },
    { code: 'AH', name: 'Anhui' },
    { code: 'FJ', name: 'Fujian' },
    { code: 'JX', name: 'Jiangxi' },
    { code: 'HN', name: 'Henan' },
    { code: 'HB', name: 'Hubei' },
    { code: 'HUN', name: 'Hunan' },
    { code: 'GD', name: 'Guangdong' },
    { code: 'GX', name: 'Guangxi (Autonomous Region)' },
    { code: 'HAIN', name: 'Hainan' },
    { code: 'SC', name: 'Sichuan' },
    { code: 'GZ', name: 'Guizhou' },
    { code: 'YN', name: 'Yunnan' },
    { code: 'XZ', name: 'Tibet (Autonomous Region)' },
    { code: 'SN', name: 'Shaanxi' },
    { code: 'GS', name: 'Gansu' },
    { code: 'QH', name: 'Qinghai' },
    { code: 'NX', name: 'Ningxia (Autonomous Region)' },
    { code: 'XJ', name: 'Xinjiang (Autonomous Region)' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'HK', name: 'Hong Kong (SAR)' },
    { code: 'MO', name: 'Macau (SAR)' }
  ];
  
  // Japan Prefectures
  export const japanPrefectures = [
    { code: 'JP-01', name: 'Hokkaido' },
    { code: 'JP-02', name: 'Aomori' },
    { code: 'JP-03', name: 'Iwate' },
    { code: 'JP-04', name: 'Miyagi' },
    { code: 'JP-05', name: 'Akita' },
    { code: 'JP-06', name: 'Yamagata' },
    { code: 'JP-07', name: 'Fukushima' },
    { code: 'JP-08', name: 'Ibaraki' },
    { code: 'JP-09', name: 'Tochigi' },
    { code: 'JP-10', name: 'Gunma' },
    { code: 'JP-11', name: 'Saitama' },
    { code: 'JP-12', name: 'Chiba' },
    { code: 'JP-13', name: 'Tokyo' },
    { code: 'JP-14', name: 'Kanagawa' },
    { code: 'JP-15', name: 'Niigata' },
    { code: 'JP-16', name: 'Toyama' },
    { code: 'JP-17', name: 'Ishikawa' },
    { code: 'JP-18', name: 'Fukui' },
    { code: 'JP-19', name: 'Yamanashi' },
    { code: 'JP-20', name: 'Nagano' },
    { code: 'JP-21', name: 'Gifu' },
    { code: 'JP-22', name: 'Shizuoka' },
    { code: 'JP-23', name: 'Aichi' },
    { code: 'JP-24', name: 'Mie' },
    { code: 'JP-25', name: 'Shiga' },
    { code: 'JP-26', name: 'Kyoto' },
    { code: 'JP-27', name: 'Osaka' },
    { code: 'JP-28', name: 'Hyogo' },
    { code: 'JP-29', name: 'Nara' },
    { code: 'JP-30', name: 'Wakayama' },
    { code: 'JP-31', name: 'Tottori' },
    { code: 'JP-32', name: 'Shimane' },
    { code: 'JP-33', name: 'Okayama' },
    { code: 'JP-34', name: 'Hiroshima' },
    { code: 'JP-35', name: 'Yamaguchi' },
    { code: 'JP-36', name: 'Tokushima' },
    { code: 'JP-37', name: 'Kagawa' },
    { code: 'JP-38', name: 'Ehime' },
    { code: 'JP-39', name: 'Kochi' },
    { code: 'JP-40', name: 'Fukuoka' },
    { code: 'JP-41', name: 'Saga' },
    { code: 'JP-42', name: 'Nagasaki' },
    { code: 'JP-43', name: 'Kumamoto' },
    { code: 'JP-44', name: 'Oita' },
    { code: 'JP-45', name: 'Miyazaki' },
    { code: 'JP-46', name: 'Kagoshima' },
    { code: 'JP-47', name: 'Okinawa' }
  ];
  
  // Country Codes
  export const countries = [
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'US', name: 'United States' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'FR', name: 'France' },
    { code: 'DE', name: 'Germany' },
    { code: 'IN', name: 'India' },
    { code: 'CN', name: 'China' },
    { code: 'JP', name: 'Japan' },
    { code: 'SA', name: 'Saudi Arabia' }
  ];
  